name: Changelog

on:
  workflow_run:
    workflows: Release
    types: completed

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npx conventional-changelog-cli -p conventionalcommits -o CHANGELOG.md -r 2
      - run: echo "RELEASE_NAME=$(gh release list --json name,isLatest --jq '.[] | select(.isLatest)|.name')" >> $GITHUB_ENV
      - run: gh release edit $RELEASE_NAME --notes-file CHANGELOG.md
